# Generated by Django 2.0 on 2017-12-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_title', models.CharField(max_length=80)),
                ('txt_body', models.TextField()),
                ('txt_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Author')),
            ],
        ),
    ]
