# Generated by Django 2.0 on 2018-01-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_author_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
