# Generated by Django 2.0 on 2018-01-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20180107_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(upload_to='static/page'),
        ),
    ]
