# Generated by Django 2.0 on 2018-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20180107_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='txt_date',
            field=models.DateTimeField(null=True, verbose_name='published'),
        ),
    ]
