# Generated by Django 2.0 on 2018-01-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_content_txt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='txt_date',
            field=models.DateTimeField(verbose_name='published'),
        ),
    ]
