# Generated by Django 2.0 on 2018-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20180107_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='txt_tag',
            field=models.ManyToManyField(to='page.Tag'),
        ),
    ]
