# Generated by Django 2.0 on 2018-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20180107_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='wchat',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
