# Generated by Django 2.0 on 2018-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_auto_20180107_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='wchat',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
