# Generated by Django 2.0 on 2018-01-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20180107_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='wchat',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
